---
title: "Assessment"
output: html_document
date: "2025-11-12"
---

This project aims to look at "trends in the prescribing of dry eye disease medication across the four seasons in Scotland."

Introduction-

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.show = "hold"
)
knitr::opts_knit$set(root.dir = "/Users/james/B249281")
```

```{r}
library(tidyverse)
library(janitor)
library(gt)
library(scales)
```

```{r}
prescribing_data <- list.files("data/prescribing_data", full.names = TRUE) %>% 
  set_names() %>%
  map(~ read_csv(.x) %>%
        rename(any_of(c(HBT = "HBT2014"))) %>%
        select(HBT, BNFItemCode, BNFItemDescription, GPPractice, NumberOfPaidItems, PaidQuantity, GrossIngredientCost, PaidDateMonth))

ded_prescriptions <- prescribing_data %>%
  map(~ .x %>% filter(grepl("110801", BNFItemCode))) %>%
  bind_rows() %>%
  clean_names()
```

```{r}
ded_seasonal_summary <- ded_prescriptions %>%
  mutate(month = paid_date_month %% 100, month_name = case_when(
      month == 1  ~ "January",
      month == 2  ~ "February",
      month == 3  ~ "March",
      month == 4  ~ "April",
      month == 5  ~ "May",
      month == 6  ~ "June",
      month == 7  ~ "July",
      month == 8  ~ "August",
      month == 9  ~ "September",
      month == 10 ~ "October",
      month == 11 ~ "November",
      month == 12 ~ "December")) %>%
  group_by(month_name, month) %>%
    summarise(total_paid_quantity = sum(paid_quantity)) %>%
  mutate(month_name = factor(month_name, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")),
    season = case_when(
      month %in% c(3, 4, 5)  ~ "Spring",
      month %in% c(6, 7, 8)  ~ "Summer",
      month %in% c(9, 10, 11) ~ "Autumn",
      month %in% c(12, 1, 2) ~ "Winter"))
```

```{r}
ggplot(ded_seasonal_summary, aes(x = month_name, y = total_paid_quantity, group = 1, color = season)) +
  geom_line(size = 1.2) + 
  geom_point(size = 2) +
  scale_color_manual(values = c("Spring" = "green3", "Summer" = "orange", "Autumn" = "brown1", "Winter" = "blue")) +
  labs(
    title = "Monthly Paid Quantity of Dry Eye Disease Medications (2022-2024)",
    subtitle = "Grouped by Season",
    x = "Month",
    y = "Total Paid Quantity",
    color = "Season") +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12)) +
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, linetype = "dashed", color = "black")
```

```{r}
gp_details <- read_csv("data/gp_details/0d2e258a-1451-4af1-a7e5-e8327994fa55.csv") %>%
  select(PracticeCode, DataZone, PracticeListSize) %>%
  clean_names()

urban_rural <- read_csv("data/urban_rural/c8bd76cd-6613-4dd7-8a28-6c99a16dc678.csv") %>%
  select(DataZone, UrbanRural6fold2020) %>%
  clean_names()

gp_rurality <- inner_join(gp_details, urban_rural, by = "data_zone")
```

```{r}
ded_prescriptions_by_gp <- ded_prescriptions %>%
  group_by(gp_practice) %>%
  summarise(total_paid_quantity = sum(paid_quantity, na.rm = TRUE))

ded_prescriptions_rurality <- full_join(ded_prescriptions_by_gp, gp_rurality, by = c("gp_practice" = "practice_code")) %>%
  filter(!is.na(urban_rural6fold2020)) %>%
  group_by(urban_rural6fold2020) %>%
  summarise(total_paid_quantity = sum(total_paid_quantity, na.rm = TRUE), total_practice_list_size = sum(practice_list_size, na.rm = TRUE)) %>%
  mutate(proportion_quantity = total_paid_quantity / total_practice_list_size, urban_rural6fold2020 = factor(urban_rural6fold2020, levels = 1:6, labels = c("Large Urban Areas [1]", "Other Urban Areas [2]", "Accessible Small Towns [3]", "Remote Small Towns [4]", "Accessible Rural [5]", "Remote Rural [6]")))
```

```{r}
ded_prescriptions_rurality %>%
  mutate(itemsperperson = total_paid_quantity / total_practice_list_size) %>%
  select(urbanrural = urban_rural6fold2020, total_items = total_paid_quantity, total_population = total_practice_list_size, itemsperperson) %>%
  gt() %>%
  tab_header(
    title = md("**Dry Eye Medication Prescribing by Urban–Rural Classification**"),
    subtitle = "Standardised by practice list size, Scotland (2024)") %>%
  fmt_number(
    columns = c(total_items, total_population),
    decimals = 0,
    use_seps = TRUE) %>%
  fmt_number(
    columns = itemsperperson,
    decimals = 3) %>%
  cols_label(
    urbanrural = "Urban/Rural Category",
    total_items = "Total DED Items Dispensed",
    total_population = "Total Practice Population",
    itemsperperson = "Items per Person") %>%
  tab_style(
    style = list(cell_text(weight = "bold")), locations = cells_title(groups = "title")) %>%
  tab_style(
    style = cell_borders(sides = "bottom", color = "black", weight = px(2)),
    locations = cells_column_labels()) %>%
  tab_options(
    table.font.size = 14,
    column_labels.background.color = "#f0f0f0",
    data_row.padding = px(6),
    table.border.top.color = "white",
    table.border.bottom.color = "white",
    heading.title.font.size = 20,
    heading.subtitle.font.size = 14)
```

```{r}
practice_populations <- read_csv("data/practice_populations/ce967fa9-0f7f-4389-9f19-4958c45e43c2.csv") %>%
  clean_names()
```

```{r}
ded_by_gp_2024 <- ded_prescriptions %>%
  filter(str_starts(as.character(paid_date_month), "2024")) %>%
  group_by(gp_practice) %>%
  summarise(total_paid_quantity = sum(paid_quantity, na.rm = TRUE))

sex_population <- practice_populations %>%
    group_by(sex, practice_code) %>%
    summarise(total_all_ages = sum(all_ages, na.rm = TRUE)) %>%
    pivot_wider(names_from = sex, values_from = total_all_ages) %>%
    mutate(female_to_male_ratio = Female / Male) %>%
    filter(!is.na(female_to_male_ratio))

ded_per_sex_gp_2024 <- inner_join(ded_by_gp_2024, sex_population, by = c("gp_practice" = "practice_code")) %>%
  mutate(rate_per_person = total_paid_quantity / All)
```
  
```{r}
ggplot(ded_per_sex_gp_2024, aes(x = female_to_male_ratio, y = rate_per_person, size = All)) +
  geom_point(color = "pink1", alpha = 0.7) +
  geom_smooth(method = "lm", se = TRUE, color = "black", linetype = "dashed", linewidth = 1) +
  scale_x_log10(labels = scales::comma_format(accuracy = 0.01)) +  # Prevents extreme ratios from stretching the plot and makes trends easier to see.
  scale_y_continuous(labels = scales::comma_format(accuracy = 0.01)) +
  scale_size_continuous(name = "Practice Population", range = c(2, 8)) +
  labs(
    title = "Effect of Female-to-Male Ratio on DED Prescription Rate (2024)",
    subtitle = "Each point represents a GP practice",
    x = "Female-to-Male Ratio (log scale)",
    y = "DED Items per Person",
    caption = "Source: Scottish GP prescribing data"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  )
```

```{r}
hb_pop_normalised <- practice_populations %>%
  rowwise() %>%
  mutate(
    weighted_age = (ages0to4*2.5 + ages5to14*10 + ages15to24*20 + ages25to44*34.5 + ages45to64*54.5 + ages65to74*69.5 + ages75to84*79.5 + ages85plus*90) / all_ages)

joined_hbt_DED <- inner_join(ded_by_gp_2024, hb_pop_normalised, by = c("gp_practice" = "practice_code")) %>%
  filter(sex == "All") %>%
  mutate(rate_per_person = total_paid_quantity / all_ages) %>%
    filter(!is.na(weighted_age))
```

```{r}
ggplot(joined_hbt_DED, aes(x = weighted_age, y = rate_per_person, size = all_ages)) +
  geom_point(color = "brown1", alpha = 0.7) +
  geom_smooth(method = "lm", se = TRUE, color = "black", linetype = "dashed", linewidth = 1) +
  scale_x_continuous(labels = scales::comma_format(accuracy = 0.1)) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 0.01)) +
  scale_size_continuous(name = "Practice Population", range = c(2, 8)) +
  labs(
    title = "Effect of Weighted Mean Age on DED Prescription Rate (2024)",
    subtitle = "Each point represents a GP practice",
    x = "Weighted Mean Age of Practice Population",
    y = "DED Items per Person",
    caption = "Source: Scottish GP prescribing data"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  )
```


